#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[System.Data.Linq.Mapping.DatabaseAttribute(Name="ningboBus")]
public partial class NingboBus : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  #endregion
	
	public NingboBus(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
    //public NingboBus(System.Data.IDbConnection connection) : 
    //        base(connection, mappingSource)
    //{
    //    OnCreated();
    //}
	
	public NingboBus(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
    //public NingboBus(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
    //        base(connection, mappingSource)
    //{
    //    OnCreated();
    //}
	
	public System.Data.Linq.Table<Cnbus> Cnbus
	{
		get
		{
			return this.GetTable<Cnbus>();
		}
	}
	
	public System.Data.Linq.Table<Cnbusw> Cnbusw
	{
		get
		{
			return this.GetTable<Cnbusw>();
		}
	}
	
	public System.Data.Linq.Table<Info> Info
	{
		get
		{
			return this.GetTable<Info>();
		}
	}
}

[Table(Name="cnbus")]
public partial class Cnbus
{
	
	private System.Nullable<int> _Xid;
	
	private System.Nullable<int> _Pm;
	
	private string _Zhan;
	
	private System.Nullable<byte> _Kind;
	
	private string _Azhan;
	
	public Cnbus()
	{
	}
	
	[Column(Name="xid", Storage="_Xid", DbType="Int")]
	public System.Nullable<int> Xid
	{
		get
		{
			return this._Xid;
		}
		set
		{
			if ((this._Xid != value))
			{
				this._Xid = value;
			}
		}
	}
	
	[Column(Name="pm", Storage="_Pm", DbType="Int")]
	public System.Nullable<int> Pm
	{
		get
		{
			return this._Pm;
		}
		set
		{
			if ((this._Pm != value))
			{
				this._Pm = value;
			}
		}
	}
	
	[Column(Name="zhan", Storage="_Zhan", DbType="NVarChar(40)")]
	public string Zhan
	{
		get
		{
			return this._Zhan;
		}
		set
		{
			if ((this._Zhan != value))
			{
				this._Zhan = value;
			}
		}
	}
	
	[Column(Name="kind", Storage="_Kind", DbType="TinyInt")]
	public System.Nullable<byte> Kind
	{
		get
		{
			return this._Kind;
		}
		set
		{
			if ((this._Kind != value))
			{
				this._Kind = value;
			}
		}
	}
	
	[Column(Name="azhan", Storage="_Azhan", DbType="NVarChar(20)")]
	public string Azhan
	{
		get
		{
			return this._Azhan;
		}
		set
		{
			if ((this._Azhan != value))
			{
				this._Azhan = value;
			}
		}
	}
}

[Table(Name="cnbusw")]
public partial class Cnbusw
{
	
	private System.Nullable<int> _Id;
	
	private string _Busw;
	
	private string _Shijian;
	
	private string _Zxdate;
	
	private string _Kind;
	
	private string _Gjgs;
	
	private System.Nullable<byte> _J;
	
	private string _Note;
	
	private string _Piao;
	
	private System.Nullable<int> _Shuzi;
	
	public Cnbusw()
	{
	}
	
	[Column(Name="id", Storage="_Id", DbType="Int")]
	public System.Nullable<int> Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this._Id = value;
			}
		}
	}
	
	[Column(Name="busw", Storage="_Busw", DbType="NVarChar(40)")]
	public string Busw
	{
		get
		{
			return this._Busw;
		}
		set
		{
			if ((this._Busw != value))
			{
				this._Busw = value;
			}
		}
	}
	
	[Column(Name="shijian", Storage="_Shijian", DbType="NVarChar(250)")]
	public string Shijian
	{
		get
		{
			return this._Shijian;
		}
		set
		{
			if ((this._Shijian != value))
			{
				this._Shijian = value;
			}
		}
	}
	
	[Column(Name="zxdate", Storage="_Zxdate", DbType="NVarChar(20)")]
	public string Zxdate
	{
		get
		{
			return this._Zxdate;
		}
		set
		{
			if ((this._Zxdate != value))
			{
				this._Zxdate = value;
			}
		}
	}
	
	[Column(Name="kind", Storage="_Kind", DbType="NVarChar(24)")]
	public string Kind
	{
		get
		{
			return this._Kind;
		}
		set
		{
			if ((this._Kind != value))
			{
				this._Kind = value;
			}
		}
	}
	
	[Column(Name="gjgs", Storage="_Gjgs", DbType="NVarChar(100)")]
	public string Gjgs
	{
		get
		{
			return this._Gjgs;
		}
		set
		{
			if ((this._Gjgs != value))
			{
				this._Gjgs = value;
			}
		}
	}
	
	[Column(Name="j", Storage="_J", DbType="TinyInt")]
	public System.Nullable<byte> J
	{
		get
		{
			return this._J;
		}
		set
		{
			if ((this._J != value))
			{
				this._J = value;
			}
		}
	}
	
	[Column(Name="note", Storage="_Note", DbType="NText", UpdateCheck=UpdateCheck.Never)]
	public string Note
	{
		get
		{
			return this._Note;
		}
		set
		{
			if ((this._Note != value))
			{
				this._Note = value;
			}
		}
	}
	
	[Column(Name="piao", Storage="_Piao", DbType="NVarChar(200)")]
	public string Piao
	{
		get
		{
			return this._Piao;
		}
		set
		{
			if ((this._Piao != value))
			{
				this._Piao = value;
			}
		}
	}
	
	[Column(Name="shuzi", Storage="_Shuzi", DbType="Int")]
	public System.Nullable<int> Shuzi
	{
		get
		{
			return this._Shuzi;
		}
		set
		{
			if ((this._Shuzi != value))
			{
				this._Shuzi = value;
			}
		}
	}
}

[Table(Name="info")]
public partial class Info
{
	
	private string _Lastdate;
	
	private string _Dbname;
	
	private System.Nullable<int> _Modified;
	
	private System.Nullable<byte> _Map;
	
	private System.Nullable<int> _Lastdbid;
	
	public Info()
	{
	}
	
	[Column(Name="lastdate", Storage="_Lastdate", DbType="NVarChar(14)")]
	public string Lastdate
	{
		get
		{
			return this._Lastdate;
		}
		set
		{
			if ((this._Lastdate != value))
			{
				this._Lastdate = value;
			}
		}
	}
	
	[Column(Name="dbname", Storage="_Dbname", DbType="NVarChar(100)")]
	public string Dbname
	{
		get
		{
			return this._Dbname;
		}
		set
		{
			if ((this._Dbname != value))
			{
				this._Dbname = value;
			}
		}
	}
	
	[Column(Name="modified", Storage="_Modified", DbType="Int")]
	public System.Nullable<int> Modified
	{
		get
		{
			return this._Modified;
		}
		set
		{
			if ((this._Modified != value))
			{
				this._Modified = value;
			}
		}
	}
	
	[Column(Name="map", Storage="_Map", DbType="TinyInt")]
	public System.Nullable<byte> Map
	{
		get
		{
			return this._Map;
		}
		set
		{
			if ((this._Map != value))
			{
				this._Map = value;
			}
		}
	}
	
	[Column(Name="lastdbid", Storage="_Lastdbid", DbType="Int")]
	public System.Nullable<int> Lastdbid
	{
		get
		{
			return this._Lastdbid;
		}
		set
		{
			if ((this._Lastdbid != value))
			{
				this._Lastdbid = value;
			}
		}
	}
}
#pragma warning restore 1591
